package win_687rhjv6vul._19086.teamworks.webservices.oppod.wfmcoordinationeventservice_tws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-03-09T12:14:43.852-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "WFMCoordinationEventService", 
                  wsdlLocation = "http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws?wsdl",
                  targetNamespace = "http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws") 
public class WFMCoordinationEventService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws", "WFMCoordinationEventService");
    public final static QName WFMCoordinationEventServiceSoap = new QName("http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws", "WFMCoordinationEventServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WFMCoordinationEventService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WFMCoordinationEventService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WFMCoordinationEventService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFMCoordinationEventService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * SOAP Port   
     *
     * @return
     *     returns WFMCoordinationEventServicePortType
     */
    @WebEndpoint(name = "WFMCoordinationEventServiceSoap")
    public WFMCoordinationEventServicePortType getWFMCoordinationEventServiceSoap() {
        return super.getPort(WFMCoordinationEventServiceSoap, WFMCoordinationEventServicePortType.class);
    }

    /**
     * SOAP Port   
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WFMCoordinationEventServicePortType
     */
    @WebEndpoint(name = "WFMCoordinationEventServiceSoap")
    public WFMCoordinationEventServicePortType getWFMCoordinationEventServiceSoap(WebServiceFeature... features) {
        return super.getPort(WFMCoordinationEventServiceSoap, WFMCoordinationEventServicePortType.class, features);
    }

}
