
package win_687rhjv6vul._19086.teamworks.webservices.oppod.wfmcoordinationeventservice_tws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-03-09T12:14:43.757-05:00
 * Generated source version: 2.4.6
 * 
 */
public final class WFMCoordinationEventServicePortType_WFMCoordinationEventServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://WIN-687RHJV6VUL:19086/teamworks/webservices/OPPOD/WFMCoordinationEventService.tws", "WFMCoordinationEventService");

    private WFMCoordinationEventServicePortType_WFMCoordinationEventServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WFMCoordinationEventService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WFMCoordinationEventService ss = new WFMCoordinationEventService(wsdlURL, SERVICE_NAME);
        WFMCoordinationEventServicePortType port = ss.getWFMCoordinationEventServiceSoap();  
        
        {
        System.out.println("Invoking orderExecutionCompleted...");
        java.lang.String _orderExecutionCompleted_patientID = "";
        java.lang.String _orderExecutionCompleted_timestamp = "";
        port.orderExecutionCompleted(_orderExecutionCompleted_patientID, _orderExecutionCompleted_timestamp);


        }
        {
        System.out.println("Invoking consultationCompleted2...");
        java.lang.String _consultationCompleted2_patientID = "";
        java.lang.String _consultationCompleted2_physicianID = "";
        java.lang.String _consultationCompleted2_locationID = "";
        java.lang.String _consultationCompleted2_timestamp = "";
        port.consultationCompleted2(_consultationCompleted2_patientID, _consultationCompleted2_physicianID, _consultationCompleted2_locationID, _consultationCompleted2_timestamp);


        }
        {
        System.out.println("Invoking waitForConsultation2...");
        java.lang.String _waitForConsultation2_patientID = "";
        java.lang.String _waitForConsultation2_locationID = "";
        java.lang.String _waitForConsultation2_timestamp = "";
        port.waitForConsultation2(_waitForConsultation2_patientID, _waitForConsultation2_locationID, _waitForConsultation2_timestamp);


        }
        {
        System.out.println("Invoking patientAdmittedWithBed...");
        java.lang.String _patientAdmittedWithBed_patientID = "";
        java.lang.String _patientAdmittedWithBed_unitID = "";
        java.lang.String _patientAdmittedWithBed_bedID = "";
        java.lang.String _patientAdmittedWithBed_timestamp = "";
        port.patientAdmittedWithBed(_patientAdmittedWithBed_patientID, _patientAdmittedWithBed_unitID, _patientAdmittedWithBed_bedID, _patientAdmittedWithBed_timestamp);


        }
        {
        System.out.println("Invoking consultationStarted1...");
        java.lang.String _consultationStarted1_patientID = "";
        java.lang.String _consultationStarted1_physicianID = "";
        java.lang.String _consultationStarted1_locationID = "";
        java.lang.String _consultationStarted1_timestamp = "";
        port.consultationStarted1(_consultationStarted1_patientID, _consultationStarted1_physicianID, _consultationStarted1_locationID, _consultationStarted1_timestamp);


        }
        {
        System.out.println("Invoking consultationStarted2...");
        java.lang.String _consultationStarted2_patientID = "";
        java.lang.String _consultationStarted2_physicianID = "";
        java.lang.String _consultationStarted2_locationID = "";
        java.lang.String _consultationStarted2_timestamp = "";
        port.consultationStarted2(_consultationStarted2_patientID, _consultationStarted2_physicianID, _consultationStarted2_locationID, _consultationStarted2_timestamp);


        }
        {
        System.out.println("Invoking orderRequest...");
        java.lang.String _orderRequest_patientID = "";
        java.lang.String _orderRequest_providerID = "";
        java.lang.String _orderRequest_orderType = "";
        java.lang.String _orderRequest_orderID = "";
        java.lang.String _orderRequest_timestamp = "";
        port.orderRequest(_orderRequest_patientID, _orderRequest_providerID, _orderRequest_orderType, _orderRequest_orderID, _orderRequest_timestamp);


        }
        {
        System.out.println("Invoking patientAdmittedWithNoBed...");
        java.lang.String _patientAdmittedWithNoBed_patientID = "";
        java.lang.String _patientAdmittedWithNoBed_unitID = "";
        java.lang.String _patientAdmittedWithNoBed_timestamp = "";
        port.patientAdmittedWithNoBed(_patientAdmittedWithNoBed_patientID, _patientAdmittedWithNoBed_unitID, _patientAdmittedWithNoBed_timestamp);


        }
        {
        System.out.println("Invoking waitForOrderExecution...");
        java.lang.String _waitForOrderExecution_patientID = "";
        java.lang.String _waitForOrderExecution_timestamp = "";
        port.waitForOrderExecution(_waitForOrderExecution_patientID, _waitForOrderExecution_timestamp);


        }
        {
        System.out.println("Invoking orderRequestCompleted...");
        java.lang.String _orderRequestCompleted_patientID = "";
        java.lang.String _orderRequestCompleted_providerID = "";
        java.lang.String _orderRequestCompleted_orderType = "";
        java.lang.String _orderRequestCompleted_orderID = "";
        java.lang.String _orderRequestCompleted_timestamp = "";
        port.orderRequestCompleted(_orderRequestCompleted_patientID, _orderRequestCompleted_providerID, _orderRequestCompleted_orderType, _orderRequestCompleted_orderID, _orderRequestCompleted_timestamp);


        }
        {
        System.out.println("Invoking waitForBed...");
        java.lang.String _waitForBed_patientID = "";
        java.lang.String _waitForBed_unitID = "";
        java.lang.String _waitForBed_timestamp = "";
        port.waitForBed(_waitForBed_patientID, _waitForBed_unitID, _waitForBed_timestamp);


        }
        {
        System.out.println("Invoking patientArriveInBed...");
        java.lang.String _patientArriveInBed_patientID = "";
        java.lang.String _patientArriveInBed_bedID = "";
        java.lang.String _patientArriveInBed_unitID = "";
        java.lang.String _patientArriveInBed_timestamp = "";
        port.patientArriveInBed(_patientArriveInBed_patientID, _patientArriveInBed_bedID, _patientArriveInBed_unitID, _patientArriveInBed_timestamp);


        }
        {
        System.out.println("Invoking patientTransportRequest...");
        java.lang.String _patientTransportRequest_patientID = "";
        java.lang.String _patientTransportRequest_providerID = "";
        java.lang.String _patientTransportRequest_unitID = "";
        java.lang.String _patientTransportRequest_timestamp = "";
        port.patientTransportRequest(_patientTransportRequest_patientID, _patientTransportRequest_providerID, _patientTransportRequest_unitID, _patientTransportRequest_timestamp);


        }
        {
        System.out.println("Invoking waitForConsultation1...");
        java.lang.String _waitForConsultation1_patientID = "";
        java.lang.String _waitForConsultation1_locationID = "";
        java.lang.String _waitForConsultation1_timestamp = "";
        port.waitForConsultation1(_waitForConsultation1_patientID, _waitForConsultation1_locationID, _waitForConsultation1_timestamp);


        }
        {
        System.out.println("Invoking consultationCompleted1...");
        java.lang.String _consultationCompleted1_patientID = "";
        java.lang.String _consultationCompleted1_physicianID = "";
        java.lang.String _consultationCompleted1_locationID = "";
        java.lang.String _consultationCompleted1_timestamp = "";
        port.consultationCompleted1(_consultationCompleted1_patientID, _consultationCompleted1_physicianID, _consultationCompleted1_locationID, _consultationCompleted1_timestamp);


        }
        {
        System.out.println("Invoking triageScore...");
        java.lang.String _triageScore_patientID = "";
        java.lang.String _triageScore_providerID = "";
        java.lang.String _triageScore_ctas = "";
        java.lang.String _triageScore_timestamp = "";
        port.triageScore(_triageScore_patientID, _triageScore_providerID, _triageScore_ctas, _triageScore_timestamp);


        }
        {
        System.out.println("Invoking waitForTransport...");
        java.lang.String _waitForTransport_patientID = "";
        java.lang.String _waitForTransport_unitID = "";
        java.lang.String _waitForTransport_timestamp = "";
        port.waitForTransport(_waitForTransport_patientID, _waitForTransport_unitID, _waitForTransport_timestamp);


        }
        {
        System.out.println("Invoking patientRegistered...");
        java.lang.String _patientRegistered_patientID = "";
        java.lang.String _patientRegistered_roomID = "";
        java.lang.String _patientRegistered_timestamp = "";
        port.patientRegistered(_patientRegistered_patientID, _patientRegistered_roomID, _patientRegistered_timestamp);


        }
        {
        System.out.println("Invoking patientTransportStarted...");
        java.lang.String _patientTransportStarted_patientID = "";
        java.lang.String _patientTransportStarted_unitID = "";
        java.lang.String _patientTransportStarted_timestamp = "";
        port.patientTransportStarted(_patientTransportStarted_patientID, _patientTransportStarted_unitID, _patientTransportStarted_timestamp);


        }
        {
        System.out.println("Invoking bedRequest...");
        java.lang.String _bedRequest_patientID = "";
        java.lang.String _bedRequest_providerID = "";
        java.lang.String _bedRequest_unitID = "";
        java.lang.String _bedRequest_timestamp = "";
        port.bedRequest(_bedRequest_patientID, _bedRequest_providerID, _bedRequest_unitID, _bedRequest_timestamp);


        }

        System.exit(0);
    }

}
